### PR TITLE
Feature/gitlabci

### PR DESCRIPTION
**Pull request by white238**
Converts existing Bamboo CI job to Gitlab CI.  Thanks @keithhealy !

### CODE REVIEW

**Comment by white238** [comment]
LGTM

**Review by kennyweiss — APPROVED** [review]
Thanks @white238  and @keithhealy !

**Comment by white238** [comment]
Mirroring is messed up. Currently working with @adrienbernede to fix it!

**Comment by white238** [comment]
LGTM

**Comment by white238** [comment]
LGTM

**Comment by white238** [comment]
LGTM

**Comment by white238** [comment]
LGTM

**Comment by white238** [comment]
LGTM

**Comment by white238** [comment]
LGTM

**Comment by white238** [comment]
LGTM

**Comment by white238** [comment]
LGTM

**Comment by white238** [comment]
LGTM

**Comment by white238** [comment]
LGTM

**Comment by white238** [comment]
LGTM

**Comment by white238** [comment]
LGTM

**Comment by white238** [comment]
LGTM

**Comment by white238** [comment]
LGTM

**Pull request merged**
