### PR TITLE
fix for blt hip includes

### PR DESCRIPTION
**Pull request by dtaller**
Fix for hip-enabled builds

When improving +hip support in spack, I ran into the following error:

  >> 54    CMake Error in src/chai/CMakeLists.txt:
     55      Imported target "umpire" includes non-existent path
     56   
     57        "/opt/rocm/hip/hcc/include"
     58   
     59      in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:
     60   

I added a check to see if /opt/rocm/hip/hcc/include exists before adding it to the include directories. Apparently this directory existed for older versions of the rocm library but is no longer present

### CODE REVIEW

**Review by white238 — APPROVED** [review]
Thanks for the fix @dtaller ! If HCC is really deprecated we might want to just remove a lot of this logic at some point but future PR.

**Comment by rhornung67** [comment]
> Thanks for the fix @dtaller ! If HCC is really deprecated we might want to just remove a lot of this logic at some point but future PR.

I think we should keep it until HIP is supported in the compilers we care about for El Cap.

**Comment by davidbeckingsale** [comment]
HCC ceased development in June 2019. I think it can be removed.

**Review by davidbeckingsale — APPROVED** [review]

**Comment by white238** [comment]
Add a comment in the RELEASE-NOTES.md under the "changed" section then you can merge it once it passes tests again.  Something like "Only add HCC include directory if it exists" is just fine.

**Comment by dtaller** [comment]
> Add a comment in the RELEASE-NOTES.md under the "changed" section then you can merge it once it passes tests again. Something like "Only add HCC include directory if it exists" is just fine.

Will do, no problem

**Pull request merged**
