### PR TITLE
Moves host-configs to root directory and reorganizes test directories

### PR DESCRIPTION
**Pull request by kennyweiss**
* mv ./blt-test/host-configs to ./host-configs
* mv ./docs/tutorial/host-configs to ./host-configs
* mv smoke tests into tests/smoke and update paths
* mv internal tests into tests/internal and update paths
* update travis and appveyor scripts

### CODE REVIEW

**Comment by kennyweiss** [comment]
Addresses issue #141

**Comment by kennyweiss** [comment]
Getting an error with the ``blue_os`` host-config that I don't think is related to my changes.

Error is:
```bash
[ 95%] Linking CUDA executable ../../bin/t_cuda_device_call_from_kernel_exec
nvcc fatal   : Unknown option 'pthread'
make[2]: *** [src/test_cuda_device_call_from_kernel/CMakeFiles/t_cuda_device_call_from_kernel_exec.dir/build.make:89: bin/t_cuda_device_call_from_kernel_exec] Error 1
make[1]: *** [CMakeFiles/Makefile2:1529: src/test_cuda_device_call_from_kernel/CMakeFiles/t_cuda_device_call_from_kernel_exec.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

Configured with:
```bash
cmake -C ~/_to_usr_workspace/blt/host-configs/llnl-ray-blue_os-gcc\@4.9.3.cmake ~/_to_usr_workspace/blt/tests/internal/
```
Has anyone seen this? @cyrush @davidbeckingsale  @robinson96 

Do I have to do something to add pthreads ?

(Note: This PR moves the internal blt tests from ``./cmake/blt-tests`` to ``./tests/internal``)

**Comment by kennyweiss** [comment]
Looks like I ran into some of the issues in the discussion for #101 for the cuda tests on ray.

@robinson96  and @cyrush -- could you please look at ``host-configs/llnl-ray-blue_os-gcc@4.9.3.cmake``, which merges what were previously two separate host-configs (with differences in the three bottom lines).

I couldn't get the ``tests/internal`` project (previously, the ``cmake/blt-tests`` project) to compile due to a problem with ``pthreads`` (see above).

Please respond with the build/configure instructions for blt's master repo.

**Comment by kennyweiss** [comment]
Just wanted to point out one of the changes in this PR.  

It is now easy to configure the internal blt tests as follows:
```bash
export BLT_ROOT=<path/to/blt>
export BUILD_DIR=<path/to/build/dir>
export HC=llnl-quartz-toss3-gcc@4.9.3.cmake

#Create the build directory, if necessary
#mkdir -p ${BUILD_DIR}

cd ${BUILD_DIR}
cmake -C ${BLT_ROOT}/host-configs/${HC}  ${BLT_ROOT}/tests/internal
make
ctest
```

**Comment by cyrush** [comment]
@kennyweiss 
The existing host configs weren't really meant to be one-true exemplars for a given platform.
Their purpose was solely to facilitate testing and support the tutorials. 

For blue-os, I think we still want two host configs. Using nvcc for linking (instead of the native linker) isn't a general recommendation, even for blueos. 

(Hopefully we can invest some time to further vet CMake's native CUDA support soon, so we can move away from FindCUDA)

**Comment by kennyweiss** [comment]
@davidbeckingsale -- I can take care of #142 after this is merged.

**Comment by kennyweiss** [comment]
I created issue #146 to fix the llnl-ray host-config.  It is outside the scope of this PR since it is not currently working in blt's master branch.

@cyrush -- I think we can have several host-configs for ray, and this PR gives a default space to park them.

**Pull request merged**
