### PR TITLE
fix for hip build: fpic error

### PR DESCRIPTION
**Pull request by dtaller**
When building RAJA+hip with spack, I got the error below. The issue appears to be the snippet, --shared -Xcompiler '-fPIC' -g -O2 , with extra quotes around -fPIC . This fix should resolve the issue.

     121    /opt/rocm/hip/bin/hipcc -M /var/tmp/taller1/spack-stage/spack-stage-raja-develop-b4qt3dtl6mlnht4fte73dtv3r2bzkz2i/spack-src/src/MemUtil
            s_CUDA.cpp -o /tmp/taller1/spack-stage/spack-stage-raja-develop-b4qt3dtl6mlnht4fte73dtv3r2bzkz2i/spack-build-b4qt3dt/CMakeFiles/RAJA.di
            r/src/RAJA_generated_MemUtils_CUDA.cpp.o.depend.pre --amdgpu-target=gfx900 --shared -Xcompiler '-fPIC' -g -O2 -I/var/tmp/taller1/spack-
            stage/spack-stage-raja-develop-b4qt3dtl6mlnht4fte73dtv3r2bzkz2i/spack-src/include -I/tmp/taller1/spack-stage/spack-stage-raja-develop-b
            4qt3dtl6mlnht4fte73dtv3r2bzkz2i/spack-build-b4qt3dt/include -I/var/tmp/taller1/spack-stage/spack-stage-raja-develop-b4qt3dtl6mlnht4fte7
            3dtv3r2bzkz2i/spack-src/tpl/cub -I/var/tmp/taller1/spack-stage/spack-stage-raja-develop-b4qt3dtl6mlnht4fte73dtv3r2bzkz2i/spack-src/tpl/
            rocPRIM/rocprim/include -I/var/tmp/taller1/spack-stage/spack-stage-raja-develop-b4qt3dtl6mlnht4fte73dtv3r2bzkz2i/spack-src/tpl/camp/inc
            lude
  >> 122    clang-11: error: no such file or directory: ''-fPIC''
  >> 123    CMake Error at RAJA_generated_AlignedRangeIndexSetBuilders.cpp.o.cmake:143 (message):

### CODE REVIEW

**Comment by davidbeckingsale** [comment]
Do you know why it's using `HIP_NVCC_FLAGS`?

**Comment by dtaller** [comment]
> Do you know why it's using `HIP_NVCC_FLAGS`?

I do not know. The while issue was very strange. I was not able to replicate it on when building by hand. It only came up when I built through spack, even if I was in theory using the same version of blt and flags. I might also ask Greg Becker, but I am a bit mystified.

**Comment by davidbeckingsale** [comment]
HIP relies on some environment variables to determine the target it’s compiling for – so perhaps it’s an issue there.

**Comment by dtaller** [comment]
> HIP relies on some environment variables to determine the target it’s compiling for – so perhaps it’s an issue there.

Looking through the build log, I do see the hip platform listed as hcc . This means that we are NOT  __HIP_PLATFORM_NVCC__ . I will investigate more

-- Git Version: 2.29.1
-- MPI Support is OFF
-- OpenMP Support is OFF
-- CUDA Support is OFF
-- HIP Support is ON
-- Found HIP: /opt/rocm/hip (found version "3.8.20371-d1886b0b")
-- Performing Test HIP_CLANG_SUPPORTS_PARALLEL_JOBS
-- Performing Test HIP_CLANG_SUPPORTS_PARALLEL_JOBS - Success
-- HIP version:      3.8.20371-d1886b0b
-- HIP platform:     hcc

**Comment by dtaller** [comment]
> HIP relies on some environment variables to determine the target it’s compiling for – so perhaps it’s an issue there.

Hi @davidbeckingsale . Right above the section of code that I altered, there is a comment 

# If we are building a shared library, add extra flags to HIP_HIPCC_FLAGS 

However, HIP_HIPCC_FLAGS was not previously set. This is the preferred flag that should be set

I think the right thing to do is set set either HIP_HIPCC_FLAGS or HIP_NVCC_FLAGS based on the hip platform we are on, so that there is no confusion.

Also, there was an issue with spack where the raja project did not have a depends_on for camp (missing dependency), which also caused problems since this logic is for shared libraries in particular. I added a fix in https://github.com/spack/spack/pull/20070 .

**Comment by dtaller** [comment]
> > Do you know why it's using `HIP_NVCC_FLAGS`?
> 
> I do not know. The whole issue was very strange. I was not able to replicate it on when building by hand. It only came up when I built through spack, and only the develop version of blt (not previous release) even if I was in theory using the same version of blt and flags for both spack build and by hand build. I might also ask Greg Becker, but I am a bit mystified.

Hi @davidbeckingsale . I found out why this only occurs on spack builds but not our local by hand builds. HIP_NVCC_FLAGS does get appended to our flags in both cases. However, the difference is that the local build uses camp as a submodule in which case HIP_NVCC_FLAGS is an empty string (fPIC is not added) whereas spack uses it as a shared library so this fPIC string is added. 

I added the following code to BLT. Note the messages:

    # If we are building a shared library, add extra flags to HIP_HIPCC_FLAGS
    **message(STATUS "shared libs: ${_hip_build_shared_libs}")**
    if(_hip_build_shared_libs)
        list(APPEND HIP_HCC_FLAGS "-fPIC")
        list(APPEND HIP_CLANG_FLAGS "-fPIC")
        if("x${HIP_PLATFORM}" STREQUAL "xnvcc") # hip using nvcc cuda underneath
            **message(STATUS "shared libs: nvcc platform")**
            list(APPEND HIP_NVCC_FLAGS "--shared -Xcompiler '-fPIC'")
        else() # platform is hcc
            **message(STATUS "shared libs: hcc platform")**
            list(APPEND HIP_HIPCC_FLAGS "-fPIC")
        endif()
    endif()

When building with spack, we get:

corona211{taller1}52: spack install -v raja@develop%clang@amd~openmp+hip amdgpu_target=gfx900                                           ==> Warning: Missing a source id for blt@develop
==> Warning: Missing a source id for hip@3.8.20371-d1886b0b
==> Warning: Missing a source id for raja@develop
[+] /usr/tce (external cmake-3.14.5-fleamlqxvqbmofmwcjegqaqsgi6nn7wf)
[+] /opt/rocm/hip (external hip-3.8.20371-d1886b0b-yop5tikgvj7qs5quvi2kjbrjqsbdmeep)
[+] /opt/rocm (external hsa-rocr-dev-3.9.0-mqsluumpiigv3p4urrinvkswegcncig2)
[+] /opt/rocm/llvm (external llvm-amdgpu-3.9.0-t7rhs6lyfipbgogev5mr2zb2q7ddo7xb)
[+] /g/g17/taller1/CARE_SPACK/spack/opt/spack/linux-rhel7-zen2/clang-amd/blt-develop-hvmcsla62l5upqr4qqe4ectaitmz3aex
[+] /g/g17/taller1/CARE_SPACK/spack/opt/spack/linux-rhel7-zen2/clang-amd/camp-0.1.0-kqmbszjmf7x63lyqg2pp6adjgclxip23
==> Installing raja-develop-qael4dobyfrkbhmjmbfdohzc54jity3q
...
...
-- Using installed CAMP from:  /g/g17/taller1/CARE_SPACK/spack/opt/spack/linux-rhel7-zen2/clang-amd/camp-0.1.0-kqmbszjmf7x63lyqg2pp6adjgclxip23
-- shared libs: TRUE
-- shared libs: hcc platform

So we go through the shared library logic where fPIC is added to the list of flags.

When we build locally, we have,

corona211{taller1}67: cmake .. -DENABLE_HIP=ON -DHIP_ROOT_DIR=/opt/rocm/hip -DHIP_CLANG_PATH=/opt/rocm/llvm/bin/  -DCMAKE_C_COMPILER=/opt/rocm/llvm/bin/clang -DCMAKE_CXX_COMPILER=/opt/rocm/llvm/bin/clang++ -DCMAKE_BUILD_TYPE=Debug -DENABLE_GTEST_DEATH_TESTS=1 -DENABLE_BENCHMARKS=OFF -DBLT_SOURCE_DIR=/g/g17/taller1/CARE_SPACK/spack/opt/spack/linux-rhel7-zen2/clang-amd/blt-develop-hvmcsla62l5upqr4qqe4ectaitmz3aex
-- The CXX compiler identification is Clang 11.0.0
...
...
-- Using RAJA CAMP submodule.
-- shared libs: FALSE

So we do not exercise this logic at all for the local build

**Comment by dtaller** [comment]
After discussions with David, David Beckinsale recommended an alternate fix for the issue I discovered. Thanks David!

**Comment by dtaller** [comment]
Made fix so both hcc and amd will be accepted for HIP_PLATFORM, along with a comment explaining why this is needed. The comment comes from correspondence between David and the vendor. Thanks!

**Review by davidbeckingsale — APPROVED** [review]

**Comment by davidbeckingsale** [comment]
Thanks for getting this working @dtaller !

**Review by white238 — APPROVED** [review]

**Review by joshessman-llnl — APPROVED** [review]

**Comment by davidbeckingsale** [comment]
> Interesting, I wasn't aware that 4.0 had been released since 3.10 was just released (I think) yesterday

It isn't, but these CMake files came from the "develop" rocm iirc.

**Comment by joshessman-llnl** [comment]
> 
> 
> > Interesting, I wasn't aware that 4.0 had been released since 3.10 was just released (I think) yesterday
> 
> It isn't, but these CMake files came from the "develop" rocm iirc.

When it releases maybe we could make this check a little more precise with `${HIP_VERSION_MAJOR}" which FindHIP defines for us.

**Pull request merged**
