### PR TITLE
ci updates

### PR DESCRIPTION
**Pull request by cyrush**
add cmake 3.4.3 to travis testing
add appveyor for windows testing

### CODE REVIEW

**Comment by cyrush** [comment]
Appveyor build is failing b/c it is getting the `-Wextra` flag, so there is something wrong
with our custom compiler flag helper for visual studio


```
##################################################################
# Additional compiler warnings and treatment of warnings as errors
##################################################################

blt_append_custom_compiler_flag(
    FLAGS_VAR BLT_ENABLE_ALL_WARNINGS_FLAG
     DEFAULT "-Wall -Wextra"
     CLANG   "-Wall -Wextra" 
                    # Additional  possibilities for clang include: 
                    #       "-Wdocumentation -Wdeprecated -Weverything"
     MSVC    "/W4 /Wall /wd4619 /wd4668 /wd4820 /wd4571 /wd4710"
     XL      ""     # qinfo=<grp> produces additional messages on XL
                    # qflag=<x>:<x> defines min severity level to produce messages on XL
                    #     where x is i info, w warning, e error, s severe; default is: 
                    # (default is  qflag=i:i)
     )

blt_append_custom_compiler_flag(
    FLAGS_VAR BLT_WARNINGS_AS_ERRORS_FLAG
     DEFAULT  "-Werror"
     MSVC     "/WX"
     XL       "qhalt=w"       # i info, w warning, e error, s severe (default)
     )
```

**Comment by cyrush** [comment]
we may have to do a build tool check instead of a compiler check for things to work with visual studio.

Here is what I do for conduit:

```
macro(ENABLE_WARNINGS)
    # set the warning levels we want to abide by
    if("${CMAKE_BUILD_TOOL}" MATCHES "(msdev|devenv|nmake|MSBuild)")
        add_definitions(/W4)
    else()
        if ("${CMAKE_CXX_COMPILER_ID}" MATCHES "Clang" OR
            "${CMAKE_CXX_COMPILER_ID}" MATCHES "GNU"   OR
            "${CMAKE_CXX_COMPILER_ID}" MATCHES "Intel")
            # use these flags for clang, gcc, or icc
            add_definitions(-Wall -Wextra)
        endif()
    endif()
endmacro()
```

**Comment by davidbeckingsale** [comment]
That's a pain. We use the `MSVC` variable in RAJA and it is working on appveyor.

**Comment by cyrush** [comment]
@davidbeckingsale  thanks for the tip,  looked at the raja stuff -- the difference is in blt we are expecting the c++ compiler name to be MVSC (which won't work) while raja looks for the cmake var MSVC.

I think i am going to slot in the build tool check from conduit.

**Comment by cyrush** [comment]
@davidbeckingsale thanks, that worked  -- static builds on windows + appveyor are now working.

**Pull request merged**
