### PR TITLE
Add Travis badge

### PR DESCRIPTION
**Pull request by davidbeckingsale**

### CODE REVIEW

**Comment by cyrush** [comment]
sorry, I didn't mean to remove @white238 as a reviewer!

**Comment by cyrush** [comment]
Can you take a pass at adding the appveyor badge as well?

https://www.appveyor.com/docs/status-badges/

**Comment by davidbeckingsale** [comment]
I need the URL from you for that one - it's available in the project settings on Appveyor.

**Comment by cyrush** [comment]
Forgot it's under my name some how:

This is the project status one:

```
[![Build status](https://ci.appveyor.com/api/projects/status/fuaftu9mvp0y488j?svg=true)](https://ci.appveyor.com/project/cyrush/blt)
```

This is the master only status:

```
[![Build status](https://ci.appveyor.com/api/projects/status/fuaftu9mvp0y488j/branch/master?svg=true)](https://ci.appveyor.com/project/cyrush/blt/branch/master)
```

**Comment by davidbeckingsale** [comment]
Added.

**Pull request merged**
