### PR TITLE
Simplify clangformat version check

### LINKED ISSUE #499: regex match of clang-format --version output hanging
on rznevada, some users noticed their cmake process hanging. I was able to track this down to the regex match in https://github.com/LLNL/blt/blob/develop/cmake/SetupCodeChecks.cmake trying to parse the output of `clang-format --version`. I think the issue is that the Cray version of clang-format adds some unexpected strings. Compare the vanilla output:

[lee218@rzgenie2:build]$ /usr/tce/packages/clang/clang-11.0.1/bin/clang-format --version
clang-format version 11.0.1

versus the Cray version on rznevada:

[lee218@rznevada15:build]$ /opt/cray/pe/cce/12.0.0/cce-clang/x86_64/bin/clang-format --version
Cray clang-format version 12.0.0  (59041842ced75ac192c0f1331989ae45f58d7caf)

Would it be possible to modify the regex match to properly parse this output?

### PR DESCRIPTION
**Pull request by white238**
Fixes #499

### CODE REVIEW

**Review by joshessman-llnl — APPROVED** [review]
Fingers crossed that we don't run into this again :)

**Review by kennyweiss — APPROVED** [review]
Thanks @white238

**Comment by lee218llnl** [comment]
@white238 did you miss my comment about double escaping the dot '.' character? As is, your changes return this:

Cray clang-format v

**Comment by white238** [comment]
> 
> 
> @white238 did you miss my comment about double escaping the dot '.' character? As is, your changes return this:
> 
> Cray clang-format v

I did not and I can't find it in an email/issue/pr anywhere.  On the plus side it doesn't hang.

**Pull request merged**
