### PR TITLE
Update tutorial

### PR DESCRIPTION
**Pull request by white238**
https://llnl-blt.readthedocs.io/en/task-white238-updatetutorial/

Future tasks:
#465

### CODE REVIEW

**Comment by white238** [comment]
This PR is mainly for correctness and formatting.  It is in a good final state before we do a larger more overarching flow fix.

@kennyweiss and @cyrush , would you mind glancing over these changes.  Sorry, I know there is a lot.

**Comment by white238** [comment]
LGTM

**Review by cyrush — APPROVED** [review]

**Comment by cyrush** [comment]
I did a quick pass, things look good. Since we are going to do a few passes - let's get these in and we can continue to review and refine.

**Comment by white238** [comment]
> I did a quick pass, things look good. Since we are going to do a few passes - let's get these in and we can continue to review and refine.

I agree. Merged.

**Pull request merged**
