### PR TITLE
blt_add_test: fix missing executable suffix

### PR DESCRIPTION
**Pull request by jschueller**
on win32 the test extension is missing

### CODE REVIEW

**Comment by white238** [comment]
Can you give me an example of how this was causing you a problem? We have windows testing and projects on windows that use this so it is a bit surprising this is broken.

**Comment by jschueller** [comment]
I'm using the Makefile generator, so it goes in that IF instruction.
maybe you're using msvc generator so this is not tested ?

**Comment by white238** [comment]
My concern is this will break more than it fixes.  COMMAND can have multiple items in it, for example command line parameters.  Just tacking on the executable suffix to the end will not work.

Can you handle this at the level of the blt_add_test macro call like the following?

```
blt_add_exectuable(NAME foo
                                 ...)

blt_add_test(NAME foo_test
                     COMMAND foo${CMAKE_EXECUTABLE_SUFFIX} --some-command-line-option)
```

**Comment by white238** [comment]
We might be able to incorporate it in the logic above that splits the command and deals with the test executable

**Pull request closed without merging**
