### PR TITLE
prefix several BLT internal vars with _ to avoid expanding and duping…

### LINKED ISSUE #390: cuda vs pthread again
```
[  1%] Linking CXX executable ../../../tests/blt_mpi_smoke
cd /ccs/home/cyrush/2020.08.ascent/build_test/blt/tests/smoke && /gpfs/alpine/csc340/world-shared/software/ascent/2020-08-13/summit/cuda/gnu/spack/opt/spack/linux-rhel7-power9le/gcc-6.4.0/cmake-3.14.5-uk6fhxv4tu3svs5zh4lwupit7pn4z42e/bin/cmake -E cmake_link_script CMakeFiles/blt_mpi_smoke.dir/link.txt --verbose=1
/sw/summit/gcc/6.4.0/bin/g++      -O3 -DNDEBUG  SHELL:-pthread CMakeFiles/blt_mpi_smoke.dir/blt_mpi_smoke.cpp.o  -o ../../../tests/blt_mpi_smoke /autofs/nccs-svm1_sw/summit/.swci/1-compute/opt/spack/20180914/linux-rhel7-ppc64le/gcc-6.4.0/spectrum-mpi-10.3.1.2-20200121-awz2q5brde7wgdqqw4ugalrkukeub4eb/lib/libmpiprofilesupport.so /autofs/nccs-svm1_sw/summit/.swci/1-compute/opt/spack/20180914/linux-rhel7-ppc64le/gcc-6.4.0/spectrum-mpi-10.3.1.2-20200121-awz2q5brde7wgdqqw4ugalrkukeub4eb/lib/libmpi_ibm.so -lmpi_ibm_usempi /autofs/nccs-svm1_sw/summit/.swci/1-compute/opt/spack/20180914/linux-rhel7-ppc64le/gcc-6.4.0/spectrum-mpi-10.3.1.2-20200121-awz2q5brde7wgdqqw4ugalrkukeub4eb/lib/libmpi_ibm_mpifh.so 
g++: error: SHELL:-pthread: No such file or directory
```

### PR DESCRIPTION
**Pull request by cyrush**
… var contents on re-configure

resolves #390

### CODE REVIEW

**Comment by cyrush** [comment]
@white238 changes seem to be linked to these two files -- I hope thats the case, but can give this a close check?

**Comment by cyrush** [comment]
tested this branch vs where I was tripping up on this -- it resolves my issue

**Comment by white238** [comment]
blt_register_library has some documentation here:

docs/api/target.rst

That references how they are stored internally.

Also add a note in the RELEASE_NOTES.md file.

**Comment by kennyweiss** [comment]
@cyrush  -- I am confused about how renaming helps in this case.  Is there CMake magic on variables that start with an underscore? Or am I missing a line that converts variables of the form `_BLT_` to `BLT_` ?
(or something else).

**Comment by white238** [comment]
BLT_MPI_LINK_FLAGS was both a override variable and the internal variable that holds the value for the registered library.  This caused it to be reused in runs (because register library variables are cache variables).  so it was conflicting between the two logics and appending SHELL: over and over again.

**Comment by cyrush** [comment]
@white238 I think I tackled this, let me know what me think

**Pull request merged**
