### PR TITLE
Using generators so that OpenMP can be passed to nvcc compilers.

### PR DESCRIPTION
**Pull request by rblake-llnl**
With a small change to the openMP flags in BLT, I'm able to use openMP can cuda at the same.  This change will unfortunately break compatibility with Visual Studio builds, but I'm not sure that OpenMP+CUDA was working for that case anyway.

### CODE REVIEW

**Comment by gzagaris** [comment]
Very cool! I think this is an elegant solution addressing some of what was mentioned in #163 

I think, a similar strategy, employing CMake's generator expressions, can be used to resolve #175 as well.

**Comment by davidbeckingsale** [comment]
Agree, I like this solution. I would let others speak to the impact on VS though...

**Comment by rblake-llnl** [comment]
This should work for the Fortran case as well, though the logic might get more complicated.  

Someone has proposed a patch to cmake that removes the need for the if statement here:
https://gitlab.kitware.com/FloopCZ/cmake/commi/4f82199befee194aa924fd4dcdb2f4aad1f7dab6

**Comment by rblake-llnl** [comment]
Incorrect link, fixed here: 

https://gitlab.kitware.com/FloopCZ/cmake/commit/4f82199befee194aa924fd4dcdb2f4aad1f7dab6

**Comment by rblake-llnl** [comment]
Modified the pull request to support any combination of Fortran, CUDA, and openmp with a sane fallback compatible with Visual Studio builds.

**Comment by rblake-llnl** [comment]
@kennyweiss @gzagaris, The checks for this PR keep failing due to the build servers falling down.  Can someone on the team restart the build process?

**Comment by gzagaris** [comment]
Hmm... it doesn't look like I have access to restart appveyor or travis. @cyrush do you? or is there no good way to do this? Alternatively, @rblake-llnl , you could make an "empty" commit to trigger the builds and remove it later, but, I'd be surprised if there is no other way to manually trigger the checks.

**Comment by cyrush** [comment]
@rblake-llnl @gzagaris , I restarted the appveyor build.

**Comment by gzagaris** [comment]
Thanks @cyrush.

**Comment by rblake-llnl** [comment]
Still no luck.  AppVeyor gives the following error message:

> AppVeyor failed to assign job to 'gce' build environment after 3 attempt(s). The envronment is either unavailable or there are no free workers, however alternate build environment was not configured by the system administrator. Please try again later.

**Comment by cyrush** [comment]
@rblake-llnl, fighting with the ci is not fun @davidbeckingsale can we disable the required checks for this PR?

**Comment by davidbeckingsale** [comment]
@cyrush - you should be able to merge this now. Required checks can only be modified globally, so we need to turn it back on after this is merged.

**Comment by davidbeckingsale** [comment]
Required Appveyor checks re-enabled 👍

**Comment by rblake-llnl** [comment]
Thanks @cyrush and @davidbeckingsale !

**Pull request merged**
