### PR TITLE
Update google test and change directory name

### PR DESCRIPTION
**Pull request by adrienbernede**
This is a test.

### CODE REVIEW

**Comment by cyrush** [comment]
@adrienbernede  why is the extended name w/ the version misleading?

**Comment by adrienbernede** [comment]
@cyrush There are patches like:
```
thirdparty_builtin/patches/gtest-2020-10-07-interface-includes.patch:--- a/thirdparty_builtin/googletest-master-2020-01-07/googletest/CMakeLists.txt
thirdparty_builtin/patches/gtest-2020-10-07-interface-includes.patch:+++ b/thirdparty_builtin/googletest-master-2020-01-07/googletest/CMakeLists.txt
```
That suggest that the source in the google test dir may actually be newer than 2020-01-07.
Maybe I’m wrong, I admit I was "talking to myself" in this commit message.

**Comment by chapman39** [comment]
related to: https://github.com/LLNL/blt/issues/498

**Comment by chapman39** [comment]
@adrienbernede I believe if you grab a newer version of googletest the windows error will be fixed. Last week they had a PR with the "in_death_test_child_process" error https://github.com/google/googletest/pull/4164/files

**Comment by adrienbernede** [comment]
Closed in favor of #627.

**Pull request closed without merging**
