### PR TITLE
Local Branch for Pr/458

### PR DESCRIPTION
**Pull request by white238**
local branch for #458

### CODE REVIEW

**Comment by white238** [comment]
LGTM

**Review by kennyweiss — APPROVED** [review]
Thanks for the docs update.

Please give this PR a more informative title.

**Comment by white238** [comment]
This is just a local branch of @goxberry 's fork branch which cannot run our gitlab CI.

**Comment by rhornung67** [comment]
> Thanks for the docs update.
> 
> Please give this PR a more informative title.

@kennyweiss the name of the branch is probably my fault. I suggested it to Chris as part of a process to pull PR branches from forked repos into the project so Gitlab CI can run.

**Comment by white238** [comment]
yepp.. definitely @rhornung67 's fault. Maybe in the future we could name these something like "Local branch for PR/<#fork PR number>"

**Comment by white238** [comment]
so fancy.. it automatically closes the other PR and marks it as merged.

**Comment by rhornung67** [comment]
Pretty sweet, huh?

All I have left to contribute is fancy git commands.... :-(

**Pull request merged**
