### PR TITLE
fix for umpire hip-enabled build

### PR DESCRIPTION
**Pull request by dtaller**
This is a fix for the hip-enabled umpire build. We ran into an error

[ 23%] Building CXX object src/tpl/umpire/src/umpire/resource/CMakeFiles/umpire_resource.dir/HipDeviceResourceFactory.cpp.o
In file included from /g/g17/taller1/CARE_SPACK/CHAI/src/tpl/umpire/src/umpire/resource/HipDeviceResourceFactory.cpp:9:
In file included from /opt/rocm/hip/include/hip/hip_runtime.h:64:
In file included from /opt/rocm/hip/include/hip/hip_runtime_api.h:366:
/opt/rocm/hip/include/hip/hcc_detail/hip_runtime_api.h:48:10: fatal error: 'hsa/hsa.h' file not found
#include <hsa/hsa.h>
         ^~~~~~~~~~~

When trying to build umpire (NOT using spack, by hand) .

This fix was inspired by David Beckinsale's work here: https://github.com/LLNL/Umpire/blob/develop/scripts/uberenv/packages/umpire/package.py#L326 , where he sets HIP_RUNTIME_INCLUDE_DIRS . Thank you @davidbeckingsale  for your help and advice!

### CODE REVIEW

**Comment by davidbeckingsale** [comment]
@dtaller I don't think these specific tweaks should go in BLT - you should override somewhere else (like the Umpire spack package). I think that the specific include directories you need actually end up depending on the ROCM version too...

**Comment by dtaller** [comment]
> @dtaller I don't think these specific tweaks should go in BLT - you should override somewhere else (like the Umpire spack package). I think that the specific include directories you need actually end up depending on the ROCM version too...

Ok, no worries, I'll kill this pull request and make the change elsewhere

**Comment by dtaller** [comment]
> @dtaller I don't think these specific tweaks should go in BLT - you should override somewhere else (like the Umpire spack package). I think that the specific include directories you need actually end up depending on the ROCM version too...

Though actually I do not see this error with spack, only when I built by hand. The appropriate path must already have been included there

**Comment by davidbeckingsale** [comment]
😄 it's probably handled by the rocm_prefix stuff you added!

**Comment by white238** [comment]
This should be closed right?

**Pull request closed without merging**
