### PR TITLE
Adds ability to toggle elements in sphinx docs

### PR DESCRIPTION
**Pull request by kennyweiss**
Also adds blt logo to RTD

Tasks:

- [x]  Add toggle js and css elements
- [x]  Test using a toggled item in docs
- [x]  Add version of logo with transparent background

Credits: js and css for toggle-able elements adapted from code by @tomstitt

### CODE REVIEW

**Comment by kennyweiss** [comment]
Here's an example of toggling:
image

See: https://llnl-blt.readthedocs.io/en/feature-kweiss-toggle-docs/tutorial/setup_blt.html

**Comment by white238** [comment]
Can you change this in the conf.py while you are at it?  This controls the code snippet background color.

https://github.com/LLNL/blt/blob/9f024f1d3c8b0e70c92d01bc3eacfb69a847db04/docs/conf.py#L90

"default" is fine.. just not "sphinx"

**Review by cyrush — APPROVED** [review]
Looks good!

**Comment by kennyweiss** [comment]
@white238 -- good suggestion about the pygments theme. `default` is a nice improvement!

**Comment by white238** [comment]
LGTM

**Review by white238 — APPROVED** [review]
Nice improvement!

**Pull request merged**
